### ISSUE TITLE
OpenWizard does not open.

### ISSUE THREAD

**Issue by Landxhent** [drinfernoo/repository.openwizard#3]
I've installed OpenWizard repo per link provided. Has configured it's settings and wanted to launch it, but it just continiously loading. What could be the reason? Win 10 UWP Kodi 19.0 Matrix

**Comment by Landxhent** [comment]
https://paste.kodi.tv/ebetojenim here's kodi log

**Comment by drinfernoo** [comment]
Looks to be some kind of Unicode error, but hard to say what is happening exactly... Is this after you installed a build?

**Comment by Landxhent** [comment]
I've just installed repo and addon itself.
Lately I've tried restart kodi and eventually... It worked, lol. After that I've tested few more times and everything was all right. Dunno what was that. I've literally done nothing.

**Comment by drinfernoo** [comment]
Well, it's definitely not a fresh install... You've got tons of add-ons installed. That error looks like it's occuring during the error check after a build install.

**Comment by drinfernoo** [comment]
If this is still an isue, open it at https://github.com/a4k-openproject/plugin.program.openwizard/issues.
